---
on: [push]

env:
  smart_contract_folder: smart_contract

jobs:
  build_smart_contract:
    runs-on: ubuntu-latest
    name: Build Smart Contract
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install PyTeal with version
      #   uses: calsaviour/demo-algorand-action/install-pyteal@main
      #   with:
      #     python-version: "3.10"
      #     pyteal-version: "0.17.0"

      - name: Install Latest PyTeal
        uses: calsaviour/demo-algorand-action/install-pyteal@main
        with:
          python-version: "3.10"

      - name: Compile PyTeal to Teal
        run: |
          python ${{ env.smart_contract_folder }}/compile_contract.py

      - name: Setup Algorand Blockchain
        uses: calsaviour/demo-algorand-action/setup-algorand@main
        with:
          python-version: "3.10"
          teal-directory: "${{ env.smart_contract_folder }}"
          approval-program-name: marketplace_approval.teal
          clear-program-name: marketplace_clear.teal
          sandbox-note: tutorial-marketplace:uv1

      # - name: Build Algorand Contract
      #   id: build-algorand-contract
      #   uses: calsaviour/demo-algorand-github-action@master
      #   with:
      #     command: build
